### ISSUE TITLE
Create database for fabric_lakehouse is not permitted using Apache Spark in Microsoft Fabric. 

### ISSUE THREAD

**Issue by linusyoung** [MicrosoftLearning/mslearn-fabric#21] opened 2023-05-27 09:15 UTC
# Module: 01
#### Step: 1

Description of issue

I got below error message
`AnalysisException: org.apache.hadoop.hive.ql.metadata.HiveException: MetaException(message:Create database for fabric_lakehouse is not permitted using Apache Spark in Microsoft Fabric. )`

Repro steps:

1.Follow all steps upto Create a managed table
2.Run the code

**Comment by Mihai-Ac** [comment] 2023-05-29 15:45
Hello @linusyoung 

I have run the lab several times, but couldn´t reproduce the issue. The managed table is created every time without issues.
![image](https://github.com/MicrosoftLearning/mslearn-fabric/assets/110993710/3acff1c1-c3ff-4969-95cf-ee15d5694912)



Can you confirm you are using a **Trial** license mode for the workspace that you have created?
![image](https://github.com/MicrosoftLearning/mslearn-fabric/assets/110993710/6ecc8edc-616b-43e8-885b-b7498f56489a)

Also, can you reproduce this error in another workspace? if so, can you please include some screenshots?

Regards,
Mihai

**Comment by linusyoung** [comment] 2023-05-29 22:42
Hi Mihai,

I experienced the same issue from the other tutorial (Lakehouse tutorial introduction). Not sure if I missed any permission settings. 

Here is Workspace setting
![Workspace setting](https://github.com/MicrosoftLearning/mslearn-fabric/assets/1628500/597360fb-deb2-47c5-ba4c-61dad88654dd)

![Notebook 1](https://github.com/MicrosoftLearning/mslearn-fabric/assets/1628500/a71ea14a-85c8-4505-b22a-f2d29f0eea94)

![Notebook 2](https://github.com/MicrosoftLearning/mslearn-fabric/assets/1628500/4216a452-b576-4105-b26e-409e39af5a86)

**Comment by GraemeMalcolm** [comment] 2023-05-31 15:58
This looks like a permissions / configuration issue in the tenant (specifically the underlying ADLS store). We can't repro it with a clean setup, and unfortunately with an early preview service like this it can be difficult to track down the specific problem. The issue doesn't appear to be an error in the content, so closing this. If you figure out the cause of the problem in your tenant, please let us know!

**Closed by GraemeMalcolm** 2023-05-31 15:58 UTC

**Comment by linusyoung** [comment] 2023-05-31 21:29
@GraemeMalcolm,
Can you point me some direction regarding ADLS storage? In the Trial capacity, I can't find any related settings. I assume the underlying ADLS storage is configured automatically when I created a new workspace. Also, I checked the tenant setting in the Admin Portal, it does enable the Fabric Items.

**Comment by GraemeMalcolm** [comment] 2023-05-31 21:48
The storage is indeed set up automatically along with your workspace. This seems to be some sort of issue in your tenant, which could be related to things like the datacenter region where your tenant is defined or some other setting in your subscription. The lab steps themselves work when tried against a newly created tenant, so it doesn't seem like the issue is in the steps. Unfortunately, we can only support the lab content here - not the product itself. You can check regional status for the service and find FAQs for common known issues at https://support.fabric.microsoft.com/en-US/support/, or engage with the community there to try to resolve the issue you're having.

**Comment by linusyoung** [comment] 2023-06-01 08:18
@GraemeMalcolm 
Thanks for your response. I will check with our IT department to see if they can provide more information.

**Comment by jcbendernh** [comment] 2023-06-04 18:23
@linusyoung , I was running into the same problem and was able to resolve it by going into the Lakehouse Explorer of my Notebook and selected "Remove all Lakehouses" and then I added back the desired lakehouse and I was able to successfully create the delta tables in my lakehouse.  See screenshot for reference.
![Screenshot 2023-06-04 142101](https://github.com/MicrosoftLearning/mslearn-fabric/assets/16260984/a6ed48e9-694c-4a89-8fd4-5c39f318a0fc)

**Comment by michael-mertens** [comment] 2024-06-01 09:22
Thank you, @jcbendernh , your answer is about 1 year old, but the problem still occurs and your workaround still solves the problem!
