### ISSUE TITLE
Lab 08C Unexpected Indent

### ISSUE THREAD

**Issue by NomadicSquirrel** [MicrosoftLearning/mslearn-fabric#81] opened 2023-12-15 19:51 UTC
# Module: Train and track machine learning models with MLflow in Microsoft Fabric
#### Step: 01

Description of issue

There is an unexpected indent in the first code block that causes an error when attempting to run. See screenshot.

![CleanShot 2023-12-15 at 14 48 03@2x](https://github.com/MicrosoftLearning/mslearn-fabric/assets/112786403/6f7f83ed-8f6f-4b20-82d3-2939fcf34e8e)

Repro steps:

1. Navigate to https://microsoftlearning.github.io/mslearn-fabric/Instructions/Labs/08c-data-science-train.html
1. Copy the Load data into a dataframe - step. 1 code.
1. Paste Code to notebook and attempt to run.

**Comment by GraemeMalcolm** [comment] 2023-12-19 12:48
Thanks should be fixed (the cause is a bug in GitHub rendering of indented code blocks to HTML)

**Closed** 2023-12-19 12:48 UTC
